production ansible_host='${production_ip}' ansible_port='22' ansible_ssh_user='root'
registry ansible_host='${registry_ip}' ansible_port='22' ansible_ssh_user='root'
staging ansible_host='${staging_ip}' ansible_port='22' ansible_ssh_user='root'
dev ansible_host='${dev_ip}' ansible_port='22' ansible_ssh_user='root'
jenkins ansible_host='${jenkins_ip}' ansible_port='22' ansible_ssh_user='root'
