---
- hosts: all
  strategy: free
  become_user: root
  become: yes
  gather_facts: false
  tags: ['setup']
  pre_tasks:
    - name: 'Update apt get'
      raw: apt-get update

    - name: 'install python2'
      raw: apt-get -y install python python2.7
